Preapps 4190
Zimbra/installguides pull request #41
Opened 2020-02-04 12:53 UTC by shardool-gore

Preapps 4190

2020-02-04 14:01 UTC, abyshukla requested changes

2020-02-04 14:01 UTC, abyshukla commented on licenserequirements.adoc
> +A {product-short} license is required in order to use the {modern} in
A {product-short} license is required to use the {modern} in

2020-02-04 14:01 UTC, abyshukla commented on licenserequirements.adoc
> +the {product-edition-commercial} of {product-name}.
{product-name}'s {product-edition-commercial}.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +* Zimbra Touch Client, Zimbra Mobile Client, Zimbra HTML (Standard) Client have been removed from {product-name} {product-version}
"have been removed" is passive voice. Please consider:

> Zimbra Touch Client, Zimbra Mobile Client, Zimbra HTML (Standard) Client are no longer a part of {product-name} {product-version}.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +* {product-name} {product-version} currently does not support Rolling Upgrades
full stop at the end
rolling upgrades (lowercase)

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +** A {product-short} license is required in order to use the Modern Web Client in
"in order to" is too wordy. 'to' is a better replacement.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +the {product-edition-commercial} of {product-name}.
> {product-name}'s {product-edition-commercial}.

is crisper instead of 

> the {product-edition-commercial} of {product-name}.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +* {product-name} {product-version} introduces two versions of {product-short} Web Client, namely, Modern and Classic
Please consider using 'em dash' instead of 'namely'
full stop at the end

> * {product-name} {product-version} introduces two versions of {product-short} Web Client -- Modern and Classic.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +** Modern Web Client does not currently support some features like Personas, Briefcase and Dumpster. Some of these features will be added during upcoming releases. To view the detailed comparison of
full stop at the end of the sentence. Suggestion
> Modern Web Client does not currently support features like Personas, Briefcase, and Dumpster. Some of these features are part of upcoming releases. To view the detailed comparison of features supported in Modern Web Client, please refer to *Web Client Comparison* document.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +** Existing customized themes, logo branding changes, and crontab changes will not work with Modern Web Client. Branding needs to be re-configured to work with the Modern Web Client. Themes are curre
Future tense and passive voice is avoided in technical writing. Suggestion
> ** Existing customized themes, logo branding changes, and crontab changes are incompatible with, and hence do not reflect in, the Modern Web Client. Branding needs to be re-configured to work with the Modern Web Client. The web client also does not currently support themes.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +*** Existing Zimlets will continue to work in the Classic Web Client, however they will not work on Modern Web Client. There is no way to migrate the zimlets from Classic to Modern Web Client or vice
Future tense is avoided in technical writing. Suggestion
> *** Existing Zimlets work with Classic Web Client; however, they are incompatible with Modern Web Client. Currently, there is no way to migrate the zimlets from Classic to Modern Web Client or vice-versa.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +*** Zimbra Connect zimlet, Zimbra Drive zimlet and Zimbra Docs zimlet, are available for both the web clients. Seperate versions of these services need to be installed for Classic Web Client and Mode
passive voice. Suggestion
> *** Zimbra Connect zimlet, Zimbra Drive zimlet, and Zimbra Docs zimlet, are available for both the web clients. You can install separate versions of these services for Classic Web Client and Modern Web Client.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +The following tasks might need to be performed before you
passive voice. Suggestion
> You might need to perform the following tasks before the

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +Zimlets are supported on both Classic and Modern Web Clients. However, Zimlets used for Classic Web Client are not compatible with Modern Web Client. There is no way to migrate the zimlets from Class
Repeated

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +Branding needs to be re-configured to work with the Modern Web Client. Themes are currently not supported on Modern Web Client.
Repeated.

2020-02-04 14:01 UTC, abyshukla commented on upgrade.adoc
> +upgrade. After you review the tasks in this section, go to Upgrade
"please"
> please  go to Upgrade

2020-02-04 14:01 UTC, abyshukla commented on licenserequirements.adoc
> +Mobile and Touch clients have been removed from {product-name} {product-version}.
passive voice. Suggestion
> Mobile and Touch clients are no longer a part of {product-name} {product-version}.

2020-02-05 05:21 UTC, shardool-gore commented on licenserequirements.adoc
> +Mobile and Touch clients have been removed from {product-name} {product-version}.
agree. changed

2020-02-05 05:35 UTC, shardool-gore commented on upgrade.adoc
> +Branding needs to be re-configured to work with the Modern Web Client. Themes are currently not supported on Modern Web Client.
we need the repetition here.

2020-03-11 12:43 UTC, mogsdad commented on upgrade.adoc
> +** A {product-short} license is required in order to use the Modern Web Client in
Change "in order to" -> "to" throughout the document.

2020-03-12 09:31 UTC, abyshukla commented on systemrequirements.adoc
> +* Ubuntu 18.04 LTS Server Edition (64-bit), starting from Zimbra Collaboration 8.8.12 and above
Ubuntu 18.04 was GA with 8.8.15. With 8.8.12, it was still beta.

2020-03-19 08:22 UTC, abyshukla approved these changes

2020-03-19 08:22 UTC, merged